---
all:
  vars:
    ansible_user: mvsadmin
    ansible_password: mvsadmin
    ansible_become_pass: mvsadmin
    aes_version: 1.6.5-1
    interface: AUDIO
    priority: 48
    octet_1: 239
    octet_2: 69
  children:
    tap:
      children:
        gmu:
          vars:
            service_name: Lyra3.OR.TerminalApp
          hosts:
            GMU_PC_OR1:
              ansible_host: 10.3.1.30
            # GMU_PC_OR2:
            #   ansible_host: 10.3.2.30
        conference:
          vars:
            service_name: Lyra3.OR.ConferenceApp
          hosts:
            CONFERENCE_OR1:
              ansible_host: 10.3.1.35
            # CONFERENCE_OR2:
              # ansible_host: 10.3.2.35
        infopanel:
          vars:
            priority: 46
            service_name: Lyra3.Infopanel.TerminalApp
          hosts:
            INFOPANEL_OR1:
              ansible_host: 10.3.1.37
            # INFOPANEL_OR2:
              # ansible_host: 10.3.2.37

    gers:
      vars:
        priority: 46
        service_name: Lyra3.OR.GERS.API
      hosts:
        GERS1_OR1:
          ansible_host: 10.3.1.5
        GERS2_OR1:
          ansible_host: 10.3.1.6
        GERS3_OR1:
          ansible_host: 10.3.1.7
