---
all:
  vars:
    ansible_user: mvsadmin
    ansible_password: mvsadmin
    ansible_become_pass: mvsadmin
    aes_version: 1.6.5-1
    interface: SOUND
    octet_1: 239
    octet_2: 69

tap:
  hosts:
    # GMU_PC_OR1:
    #   ansible_host: 10.3.1.30
    #   priority: 48
    # CONFERENCE_OR1:
    #   ansible_host: 10.3.1.35
    #   priority: 48
    # INFOPANEL_OR1:
    #   ansible_host: 10.3.1.37
    #   priority: 46
    # GMU_PC_OR2:
    #   ansible_host: 10.3.2.30
    #   priority: 48
    # CONFERENCE_OR2:
    #   ansible_host: 10.3.2.35
    #   priority: 48
    # INFOPANEL_OR2:
    #   ansible_host: 10.3.2.37
    #   priority: 46